name: Detect Release
on:
  create:
      branches:
        - release/*
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@0.1.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
   # - name: GitHub Pull Request Action
   #   uses: repo-sync/pull-request@v2.0.1
   #   with:
        # Branch name to sync to in this repo, default is master
   #     destination_branch: master
   #     pr_title: "Release: ${{ github.ref }} ${{ github.branch }} ${{ github.event }}"
   #     pr_body: "## Release Checklist \n - build new manifests for ./release/ directory \n - push new tagged containers to gcr.io/google-samples/microservices-demo \n - push new git tag to repo \n\n changes since last: \n https://github.com/DanSanche/microservices-demo/compare/tags/${{ steps.previoustag.outputs.tag }}...${{ github.ref }}"
        #pr_label: release
   #     github_token: ${{ secrets.GITHUB_TOKEN }}
