name: Detect Release
on:
  create:
      branches:
        - release/*
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.0.1
      with:
        # Branch name to sync to in this repo, default is master
        destination_branch: master
        pr_body: "Staged release. When merged, a new tag will automatially be pushed. Remember to re-run ./hack/make-release-artifacts.sh if you make any updates to container images."
        #pr_label: release
        github_token: ${{ secrets.GITHUB_TOKEN }}
