name: Detect Release
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Check Test Cluster
      run: |
        pwd
        ls
        hub pull-request
