name: Detect Release
on:
  create:
      branches:
        - release/*
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: pull-request-action
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_PREFIX: "release/"
        PULL_REQUEST_BRANCH: "master"
        PULL_REQUEST_BODY: "## Release Checklist \n - build new manifests for ./release/ directory \n - push new tagged containers to gcr.io/google-samples/microservices-demo \n - push new git tag to repo \n\n changes since last: \n https://github.com/DanSanche/microservices-demo/compare/tags/${{ steps.tagName.outputs.tag }}...${{ github.ref }}"
