name: "System Smoke Tests"
on: [pull_request, push]

jobs:
  kind:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Check Test Cluster
      run: |
        if kubectl get nodes; then
          kubectl get nodes
        else
          echo "test cluster not active. Attempting to create through kind..."
          kind create cluster
          kubectl get nodes
        fi
    - name: Clean Cluster
      run: |
        kubectl delete all --all
    - name: Deploy From Source
      run: |
        skaffold run
        sleep 30
        kubectl get pods
        echo waiting for ready state...
        kubectl wait --for=condition=ready pod --timeout=600s  --all
    - name: Test HTTP
      run: |
        RESULT=$(kubectl exec deployments/frontend -- sh -c "wget --spider -S "http://frontend" 2>&1 | grep 'HTTP/'")
        echo "front end response: $RESULT"
        if [[ "$RESULT" != "  HTTP/1.1 200 OK" ]]; then 
          exit 1
        fi
    - name: Clean Cluster
      run: |
        kubectl delete all --all
    - name: Deploy Release Manifests
      run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        sleep 30
        kubectl get pods
        echo waiting for ready state...
        kubectl wait --for=condition=ready pod --timeout=600s  --all
    - name: Test HTTP
      run: |
        RESULT=$(kubectl exec deployments/frontend -- sh -c "wget --spider -S "http://frontend" 2>&1 | grep 'HTTP/'")
        echo "front end response: $RESULT"
        if [[ "$RESULT" != "  HTTP/1.1 200 OK" ]]; then 
          exit 1
        fi
