name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
      with:
          version: "v0.7.0"
    - name: Deploy
      run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        kubectl get pods
