name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    #- uses: engineerd/setup-kind@v0.3.0
    #  with:
    #      version: "v0.7.0"
    - name: Build Containers
      run: |
        #for d in ./src/* ; do
        #  echo "$d"
        #done
        skaffold run
        sleep 30
        kubectl get pods
        echo waiting for ready state...
        kubectl wait --for=condition=ready pod --timeout=600s  --all
    - name: Clean Cluster
      run: |
        kubectl delete deployments --all
        kubectl delete svc --all
    - name: Deploy Release
      run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        sleep 30
        kubectl get pods
        echo waiting for ready state...
        kubectl wait --for=condition=ready pod --timeout=600s  --all
    - name: Test HTTP
      run: |
        RESULT=$(kubectl exec deployments/frontend -- sh -c "wget --spider -S "http://frontend" 2>&1 | grep 'HTTP/'")
        echo "front end response: $RESULT"
        if [[ "$RESULT" != "  HTTP/1.1 200 OK" ]]; then 
          exit 1
        fi
