name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
      with:
          version: "v0.7.0"
    - name: Deploy
      run: |
        kubectl apply -f ./release/kubernetes-manifests.yaml
        sleep 20
        kubectl get pods
        watch kubectl get pods
        #kubectl wait --for=condition=ready pod --timeout=600s  --all
    - name: Test HTTP
      run: |
        kubectl exec deployments/frontend -- sh -c "wget --spider -S "http://frontend" 2>&1 | grep 'HTTP/'" 
