name: "Tag Release"

on: pull_request

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: get-tag
      id: get-tag
      #if: github.event.action != 'closed'
      run: |
        REF=${{ github.event.pull_request.head.ref }}
        TAG=${REF#"release/"}
        echo $TAG
        echo "##[set-output name=tag;]$TAG" 
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.get-tag.outputs.tag }}"
